#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BuglyDemo.Resource", IsApplication=true)]

namespace BuglyDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040018
			public const int app_name = 2130968600;
			
			// aapt resource value: 0x7f040000
			public const int strNetworkTipsCancelBtn = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int strNetworkTipsConfirmBtn = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int strNetworkTipsMessage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int strNetworkTipsTitle = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int strNotificationClickToContinue = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int strNotificationClickToInstall = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int strNotificationClickToRetry = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int strNotificationClickToView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int strNotificationDownloadError = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int strNotificationDownloadSucc = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int strNotificationDownloading = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int strNotificationHaveNewVersion = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int strToastCheckUpgradeError = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int strToastCheckingUpgrade = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int strToastYourAreTheLatestVersion = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int strUpgradeDialogCancelBtn = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int strUpgradeDialogContinueBtn = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int strUpgradeDialogFeatureLabel = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int strUpgradeDialogFileSizeLabel = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int strUpgradeDialogInstallBtn = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int strUpgradeDialogRetryBtn = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int strUpgradeDialogUpdateTimeLabel = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int strUpgradeDialogUpgradeBtn = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int strUpgradeDialogVersionLabel = 2130968599;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f030000
			public const int provider_paths = 2130903040;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
