#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JPush.Resource", IsApplication=true)]

namespace JPush
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int border_bg = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int bottom_bg = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_launcher_foreground = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int jpush_ic_richpush_actionbar_back = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int jpush_ic_richpush_actionbar_divider = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int jpush_notification_icon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int jpush_richpush_btn_selector = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int jpush_richpush_progressbar = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int stripes = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int top_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int background = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int getRegistrationId = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int icon = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int init = 2130903043;
			
			// aapt resource value: 0x7F030007
			public const int msg_rec = 2130903047;
			
			// aapt resource value: 0x7F030004
			public const int m_icon = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int m_text = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int m_title = 2130903046;
			
			// aapt resource value: 0x7F030008
			public const int popLayoutId = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int progress = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int push_notification_big_icon = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int push_notification_content = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int push_notification_content_one_line = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int push_notification_date = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int push_notification_dot = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int push_notification_layout_lefttop = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int push_notification_small_icon = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int push_notification_style_1 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int push_notification_style_1_big_icon = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int push_notification_style_1_content = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int push_notification_style_1_date = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int push_notification_style_1_title = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int push_notification_style_default = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int push_notification_sub_title = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int push_notification_title = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int push_root_view = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int resumePush = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int setting = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int stopPush = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int text = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int time = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int title = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int tv_appkey = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int tv_device_id = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int tv_imei = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int tv_package = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int tv_regId = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int tv_version = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int v = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int v21 = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int wvPopwin = 2130903080;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int customer_notitfication_layout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int customer_notitfication_layout_one = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int jpush_popwin_layout = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int main = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int push_notification = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int jg_channel_name_p_default = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int jg_channel_name_p_high = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int jg_channel_name_p_low = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int jg_channel_name_p_min = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MyDialogStyle = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
